site_name: fastCrypter
site_description: Fast, clean fastCrypter Python package
site_url: https://fastcrypter.readthedocs.io
repo_url: https://github.com/Pymmdrza/fastCrypter

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys, os
            - sys.path.insert(0, os.path.abspath('fastCrypter'))
          options:
            docstring_style: google
            show_source: false
            separate_signature: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
